package ch.schiemens.frontend.lexer;

public enum TokenState {

    IDENTIFIER,
    STRING_S, STRING_E, CHAR_S, CHAR_E,
    NUM_INT, INT,
    DOUBLE_S, DOUBLE_E,
    HEX_S, HEX_E,
    OCTAL_S, OCTAL_E,
    BINARY_S, BINARY_E,
    CHAR_MULTI_S, CHAR_MULTI_E, CHAR_SINGLE,
    STRING_MULTI_S, STRING_MULTI_E, STRING_SINGLE,
    S_EQ, S_LT, S_GT,
    S_EQ_EQ, S_LT_EQ, S_GT_EQ, S_NOT_EQ,
    S_PLUS, S_MINUS, S_MUL, S_DIV, S_MOD, S_EXPO, S_EXPO_MUL,
    S_AND_S, S_AND_E, S_OR_S, S_OR_E,
    S_PLUS_EQ, S_MINUS_EQ, S_MUL_EQ, S_DIV_EQ, S_MOD_EQ, S_EXPO_EQ, S_EXPO_MUL_EQ,
    S_PLUS_PLUS, S_MINUS_MINUS,
    S_ARRAY_START, S_ARRAY_END, S_CURLY_BRACKET_START, S_CURLY_BRACKET_END, S_PAREN_START, S_PAREN_END,
    S_DOT, S_NOT, S_SEMI, S_COMMA,
    S_INLINE_COMMENT, MULTI_LINE_COMMENT_S, MULTI_LINE_COMMENT_S1, MULTI_LINE_COMMENT_E,
    START, ERROR, CREATE, CREATE_B, EOF

}
